# -*- coding: utf-8 -*-
"""COINCENT PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICr1oiDn97Z6sNGLAOTuobukokskbqDj

FASHION MNIST DATA CLASSIFICATION PROJECT

step-1: import library
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import keras

"""step-2: Load data"""

(X_train, y_train), (X_test, y_test)=tf.keras.datasets.fashion_mnist.load_data()

"""print the shape of data"""

X_train.shape,y_train.shape,"***************",X_test.shape,y_test.shape

X_train[0]

y_train[0]

class_labels = ["T-shirt/top",	"Trouser",	"Pullover",	"Dress",	"Coat",	"Sandal",	"Shirt",	"Sneaker", "Bag", "Ankle boot"]

class_labels

"""Show image"""

plt.imshow(X_train[0],cmap='Greys')

plt.figure(figsize=(16,16))


j=1
for i in np.random.randint(0,1000,24):
  plt.subplot(4,6, j);j+=1
  plt.imshow(X_train[i],cmap='Greys')
  plt.axis('off')
  plt.title("{}/{}".format(class_labels[y_train[i]], y_train[i]))

#dimension
X_train.ndim

X_train = np.expand_dims(X_train,-1)

X_train.ndim

X_test=np.expand_dims(X_test,-1)

X_test.ndim

"""Features Scaling"""

X_train = X_train/255
X_test = X_test/255

"""Split DATASET"""

from sklearn.model_selection import train_test_split
X_train,X_validation,y_train,y_validation=train_test_split(X_train,y_train,test_size=0.2,random_state=2020)

X_train.shape,X_validation.shape,y_train.shape,y_validation.shape

"""Step-3:Building the CNN model"""

model=keras.models.Sequential([
                          keras.layers.Conv2D(filters=32,kernel_size=3,strides=(1,1),padding='valid',activation='relu',input_shape=[28,28,1]),
                          keras.layers.MaxPooling2D(pool_size=(2,2)),
                          keras.layers.Flatten(),
                          keras.layers.Dense(units=128,activation='relu'),
                          keras.layers.Dense(units=10,activation='softmax')
])

model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=10,batch_size=512,verbose=1,validation_data=(X_validation,y_validation))

y_pred = model.predict(X_test)
y_pred.round(2)

y_test

model.evaluate(X_test,y_test)

plt.figure(figsize=(16,16))

j=1
for i in np.random.randint(0,1000,24):
  plt.subplot(4,6, j); j+=1
  plt.imshow(X_test[i].reshape(28,28),cmap='Greys')
  plt.title('Actual = {} / {} \nPredicted = {} \ {}'.format(class_labels[y_test[i]],y_test[i], class_labels[np.argmax(y_pred[i])],np.argmax(y_pred[i])))
  plt.axis('off')

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix
plt.figure(figsize=(16,9))
y_pred_labels = [ np.argmax(label) for label in y_pred ]
cm = confusion_matrix(y_test, y_pred_labels)

sns.heatmap(cm, annot=True, fmt='d',xticklabels=class_labels, yticklabels=class_labels)

from sklearn.metrics import classification_report
cr= classification_report(y_test, y_pred_labels, target_names=class_labels)
print(cr)